services:
  - type: web
    name: secure-chat-backend
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 5001
      - key: JWT_SECRET
        generateValue: true
      - key: MONGODB_URI
        sync: false
