const mongoose = require('mongoose');

const messageSchema = new mongoose.Schema({
    senderId: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'User',
        required: true,
    },
    receiverId: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'User',
        required: true,
    },
    content: {
        type: String,
        required: true,
        // In a Secure Chat app, this content is NEVER plain text.
        // It will be an encrypted string generated by the sender's frontend
        // using the receiver's Public Key.
    },
    status: {
        type: String,
        enum: ['sent', 'delivered', 'read'],
        default: 'sent',
    }
}, {
    timestamps: true
});

module.exports = mongoose.model('Message', messageSchema);
